You won't see the **Android apk (Debug)** build option in GitHub Actions until we add a workflow file to your repository.

Here’s what you need to do:

1. **Create `.github/workflows/build-apk.yml` in your repo** with the following content:
```yaml
name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: ./gradlew assembleDebug
      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: SnakeGame-APK
          path: app/build/outputs/apk/debug/app-debug.apk
```

2. **Commit and push** this file.

3. Go to the **Actions** tab, click on **Build Android APK**, and select **Run workflow**.

4. When the run finishes, scroll to the bottom of the build log and download your `.apk` from the **Artifacts** section.

If you want, I can package the Snake game into an Android project with this workflow file ready so you just upload it and build the `.apk` directly from GitHub.
